apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-landing-page
  labels:
    app: portfolio-landing-page
    environment: prod
    tier: frontend
    release: stable
    version: v1
  namespace: bw-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-landing-page
      environment: prod
      tier: frontend
      release: stable
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1       
  template:
    metadata:
      labels:
        app: portfolio-landing-page
        environment: prod
        tier: frontend
        release: stable
        version: v1
    spec:
      containers:
      - name: portfolio-landing-page
        image: {{IMAGE}}
        imagePullPolicy: IfNotPresent
        command: ["npm","run","start"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
         ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 8
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 8
          periodSeconds: 10
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-landing-page-svc
  namespace: bw-prod
  labels:
    label: portfolio-landing-page 
    environment: prod
    tier: frontend
    release: stable
    version: v1
spec:
  type: ClusterIP
  selector:
    app: portfolio-landing-page
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 3001
    targetPort: 3001
